# Generated by Django 6.0.3 on 2026-04-08 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_rename_comment_notification_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='reciever_wallet',
            new_name='receiver_wallet',
        ),
    ]
